### ISSUE TITLE
Notification Receiving After Few Hours

### ISSUE THREAD

**Issue by PrakashParamasivam** [vjanagaran/appx#14]

**Comment by vjanagaran** [comment]
What notification? need steps to reproduce

**Comment by PrakashParamasivam** [comment]
Picture attached (chat message sent by me to my friend
![img-20150108-wa003](https://cloud.githubusercontent.com/assets/10433462/5665509/e10db1aa-9750-11e4-9b94-c92cc1a289f0.jpg)
)

**Comment by vjanagaran** [comment]
It's issue related to push functionality which we currently working. So i'm closing this
