### ISSUE TITLE
Chat Message Overlap

### ISSUE THREAD

**Issue by PrakashParamasivam** [vjanagaran/appx#8]
Chat message being overlapped in the home screen when the other user chat
![img-20150107-wa006](https://cloud.githubusercontent.com/assets/10433462/5655924/495ad08c-96cd-11e4-9130-2b770c5de01a.jpg)
![img-20150107-wa007](https://cloud.githubusercontent.com/assets/10433462/5655935/57073054-96cd-11e4-951f-b2e851eee3fd.jpg)

**Comment by vjanagaran** [comment]
It's not overlapping..... It's notification while user in app but on diff screen. we committed in between dev stage
